# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ephctrl
  tag: ""

dindImage:
  repository: ephctrl-dind
  tag: ""

tiltUpperImage:
  repository: ephctrl-tilt-upper
  tag: ""

auth:
  enabled: false

gateway:
  scheme: http
  host: preview.localhost
  tlsSecretName: ""

k3d:
  imageLoadbalancer: "rancher/k3d-proxy"
  imageTools: "rancher/k3d-tools"
  imageRegistry: "registry:2"
  imageK3s: "rancher/k3s:v1.22.6-k3s1"
