version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: gcr.io/windmill-test-containers/ephemerator-ci
    steps:
      - checkout
      - run:
          name: lint
          command: make lint
      - run:
          name: unittest
          command: make unittest
      - setup_remote_docker:
          version: 20.10.6
      - run:
          # Most of our testing is the big cluster integration tests
          name: cluster-test
          command: |
            ctlptl apply -f ephctrl/cluster.yaml
            timeout 400 tilt ci

workflows:
  test:
    jobs:
      - build
