apiVersion: apps/v1
kind: Deployment
metadata:
  name: ephctrl
  labels:
    app.kubernetes.io/name: "ephctrl"
    app.kubernetes.io/part-of: "ephemerator.tilt.dev"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "ephctrl"
      app.kubernetes.io/part-of: "ephemerator.tilt.dev"
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "ephctrl"
        app.kubernetes.io/part-of: "ephemerator.tilt.dev"
    spec:
      serviceAccountName: ephctrl-service-account
      containers:
      - name: ephctrl
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        env:
        - name: 'DIND_IMAGE'
          value: "{{ .Values.dindImage.repository }}:{{ .Values.dindImage.tag | default .Chart.AppVersion }}"
        - name: 'TILT_UPPER_IMAGE'
          value: "{{ .Values.tiltUpperImage.repository }}:{{ .Values.tiltUpperImage.tag | default .Chart.AppVersion }}"
        - name: 'EPH_ALLOWLIST'
          valueFrom:
            configMapKeyRef:
              name: ephconfig
              key: allowlist
        - name: 'EPH_GATEWAY_HOST'
          valueFrom:
            configMapKeyRef:
              name: ephconfig
              key: gatewayHost
        - name: 'K3D_IMAGE_REGISTRY'
          value: "{{ .Values.k3d.imageRegistry }}"
        - name: 'K3D_IMAGE_K3S'
          value: "{{ .Values.k3d.imageK3s }}"
        - name: 'K3D_IMAGE_LOADBALANCER'
          value: "{{ .Values.k3d.imageLoadbalancer }}"
        - name: 'K3D_IMAGE_TOOLS'
          value: "{{ .Values.k3d.imageTools }}"
          
        securityContext:
          allowPrivilegeEscalation: false
          
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
            
      terminationGracePeriodSeconds: 10
