apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ephgateway
  labels:
    app.kubernetes.io/part-of: ephemerator.tilt.dev
    app.kubernetes.io/name: ephgateway
  {{- if .Values.auth.enabled}}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "{{.Values.gateway.scheme}}://{{.Values.gateway.host}}/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "{{.Values.gateway.scheme}}://{{.Values.gateway.host}}/oauth2/sign_in?rd=http://$host$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User, X-Auth-Request-Access-Token
  {{- end}}
spec:
  ingressClassName: nginx
  rules:
  - host: {{.Values.gateway.host}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ephdash
            port:
              number: 8080
