apiVersion: v1
kind: ServiceAccount
metadata:
  name: ephctrl-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ephctrl-role
rules:
- apiGroups: [ "" ]
  resources: [ "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [ "" ]
  resources: [ "pods/exec"]
  verbs: ["create"]
- apiGroups: [ "" ]
  resources: [ "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [ "networking.k8s.io" ]
  resources: [ "ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [ "" ]
  resources: [ "configmaps" ]
  verbs: [ "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ephctrl-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ephctrl-role
subjects:
- kind: ServiceAccount
  name: ephctrl-service-account
  namespace: {{ .Release.namespace | default "default" }}
