apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  labels:
    app.kubernetes.io/part-of: ephemerator.tilt.dev
    app.kubernetes.io/name: oauth2-proxy
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app.kubernetes.io/part-of: ephemerator.tilt.dev
      app.kubernetes.io/name: oauth2-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: ephemerator.tilt.dev
        app.kubernetes.io/name: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=github
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --whitelist-domain=".{{.Values.gateway.host}}"
        - --cookie-domain="{{.Values.gateway.host}}"
        - --cookie-domain=".{{.Values.gateway.host}}"
        
        # Ensures that X-Auth-Request-User is sent to nginx
        - --pass-user-headers=true
        - --set-xauthrequest=true

        # Ensures that X-Auth-Request-Access-Token is sent to nginx
        - --pass-access-token=true
        - --set-authorization-header=true
        
        - --custom-sign-in-logo=/src/logo.svg
        {{- if .Values.github.org }}
        - --github-org={{.Values.github.org}}
        {{- end }}
        env:
        - name: 'EPH_GATEWAY_HOST'
          valueFrom:
            configMapKeyRef:
              name: ephconfig
              key: gatewayHost
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: ephoauth2
              key: OAUTH2_PROXY_CLIENT_ID
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: ephoauth2
              key: OAUTH2_PROXY_CLIENT_SECRET
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            configMapKeyRef:
              name: ephoauth2
              key: OAUTH2_PROXY_COOKIE_SECRET
        - name: OAUTH2_PROXY_COOKIE_SECURE
          valueFrom:
            configMapKeyRef:
              name: ephoauth2
              key: OAUTH2_PROXY_COOKIE_SECURE
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
