apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy
  labels:
    app.kubernetes.io/part-of: ephemerator.tilt.dev
    app.kubernetes.io/name: oauth2-proxy
spec:
{{- if .Values.gateway.tlsSecretName }}
  tls:
  - secretName: {{ .Values.gateway.tlsSecretName }}
{{- end }}
  
  ingressClassName: nginx
  rules:
  - host: {{.Values.gateway.host}}
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
