apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  labels:
    app.kubernetes.io/part-of: ephemerator.tilt.dev
    app.kubernetes.io/name: oauth2-proxy
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    app.kubernetes.io/part-of: ephemerator.tilt.dev
    app.kubernetes.io/name: oauth2-proxy
