apiVersion: v1
kind: ServiceAccount
metadata:
  name: ephctrl-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ephctrl-role
rules:
- apiGroups: [ "" ]
  resources: [ "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [ "" ]
  resources: [ "pods/exec"]
  verbs: ["create"]
- apiGroups: [ "" ]
  resources: [ "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [ "networking.k8s.io" ]
  resources: [ "ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [ "" ]
  resources: [ "configmaps" ]
  verbs: [ "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ephctrl-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ephctrl-role
subjects:
- kind: ServiceAccount
  name: ephctrl-service-account
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ephctrl
  labels:
    app.kubernetes.io/name: "ephctrl"
    app.kubernetes.io/part-of: "ephemerator.tilt.dev"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "ephctrl"
      app.kubernetes.io/part-of: "ephemerator.tilt.dev"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "ephctrl"
        app.kubernetes.io/part-of: "ephemerator.tilt.dev"
    spec:
      serviceAccountName: ephctrl-service-account
      containers:
      - image: ephctrl
        name: ephctrl
        env:
        - name: 'DIND_IMAGE'
          value: 'ephctrl-dind'
        - name: 'TILT_UPPER_IMAGE'
          value: 'ephctrl-tilt-upper'
          
        securityContext:
          allowPrivilegeEscalation: false
          
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
            
      terminationGracePeriodSeconds: 10
