load('ext://restart_process', 'docker_build_with_restart')

ingress_yaml = 'https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml'
k8s_custom_deploy(
  'ingress-nginx',
  # Only return the deployment. See:
  # https://github.com/tilt-dev/tilt/issues/5394
  apply_cmd="""
set -ex
kubectl apply -f %s 1>&2
kubectl get deployment ingress-nginx-controller -n ingress-nginx -o yaml
""" % ingress_yaml,
  delete_cmd='kubectl delete -f %s -o yaml' % ingress_yaml,
  deps=[])

docker_build(
  'ephctrl-dind',
  '.',
  only=["./dind-entrypoint.sh"],
  dockerfile='./dind.dockerfile',
  match_in_env_vars=True)

docker_build(
  'ephctrl-tilt-upper',
  '.',
  only=["./tilt-upper-entrypoint.sh", "./tilt-healthcheck.py"],
  dockerfile='./tilt-upper.dockerfile',
  match_in_env_vars=True)

local_resource(
  'ephctrl-compile',
  'make build-static',
  deps=['./cmd', './pkg'])

docker_build_with_restart(
  'ephctrl',
  '.',
  entrypoint='/usr/local/bin/ephctrl',
  dockerfile='ephctrl.dockerfile',
  only=[
    './build/ephctrl',
  ],
  live_update=[
    sync('./build/ephctrl', '/usr/local/bin/ephctrl'),
  ]
)

k8s_yaml('allowlist.yaml')
k8s_yaml('ephctrl.yaml')
k8s_yaml('ingress.yaml')
k8s_resource('ephctrl', port_forwards=['9443:9443'], resource_deps=['ephctrl-compile'])

k8s_custom_deploy(
  name='nicks-env',
  apply_cmd='kubectl apply -f configmap.yaml -o yaml',
  delete_cmd='kubectl delete -f configmap.yaml',
  deps=['configmap.yaml'])
