apiVersion: apps/v1
kind: Deployment
metadata:
  name: ephdash
  labels:
    app.kubernetes.io/name: "ephdash"
    app.kubernetes.io/part-of: "ephemerator.tilt.dev"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "ephdash"
      app.kubernetes.io/part-of: "ephemerator.tilt.dev"
  replicas: {{.Values.replicaCount}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "ephdash"
        app.kubernetes.io/part-of: "ephemerator.tilt.dev"
    spec:
      serviceAccountName: ephdash-service-account
      containers:
      - name: ephdash
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        env:
        - name: 'EPH_ALLOWLIST'
          valueFrom:
            configMapKeyRef:
              name: ephconfig
              key: allowlist
        - name: 'EPH_GATEWAY_HOST'
          valueFrom:
            configMapKeyRef:
              name: ephconfig
              key: gatewayHost
        - name: 'NAMESPACE'
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
